# Generated by Django 6.0.1 on 2026-01-10 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sku", models.CharField(max_length=50, unique=True)),
                ("current_stock", models.PositiveIntegerField(default=0)),
                ("minimum_stock_level", models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "lead_time_days",
                    models.PositiveIntegerField(
                        help_text="Average delivery time in days"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsumptionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumption_logs",
                        to="inventory.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="suppliers",
            field=models.ManyToManyField(
                related_name="products", to="inventory.supplier"
            ),
        ),
    ]
